config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'profiles#index'
  resources :profiles do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :user
end

app/models/dexterity.rb
class Dexterity < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '右投げ右打ち' },
    { id: 3, name: '右投げ左打ち' },
    { id: 4, name: '右投げ両打ち' },
    { id: 5, name: '左投げ右打ち' },
    { id: 6, name: '左投げ左打ち' },
    { id: 7, name: '左投げ両打ち' },
    { id: 8, name: '両投げ右打ち' },
    { id: 9, name: '両投げ左打ち' },
    { id: 10, name: '両投げ両打ち' },
  ]

  include ActiveHash::Associations
  has_many :profiles

  end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ピッチャー' },
    { id: 3, name: 'キャッチャー' },
    { id: 4, name: 'ファースト' },
    { id: 5, name: 'セカンド' },
    { id: 6, name: 'サード' },
    { id: 7, name: 'ショート' },
    { id: 8, name: 'レフト' },
    { id: 9, name: 'センター' },
    { id: 10, name: 'ライト' }
  ]

  include ActiveHash::Associations
  has_many :profiles

  end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :image, presence: true
  validates :position_id, presence: true, numericality: { other_than: 1 }
  validates :dexterity_id, presence: true, numericality: { other_than: 1 }
  validates :team, presence: true
  validates :age, presence: true, format: { with: /\A[0-9]+\z/ }, numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 50 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position
  belongs_to :dexterity
  belongs_to :user
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :profiles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/profiles/#{comment.profile.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, profile_id: params[:profile_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @profiles = Profile.includes(:user).order("created_at DESC")
  end

  def new
    @profile = Profile.new
  end

  def create
    Profile.create(profile_params)
  end

  def destroy
    profile = Profile.find(params[:id])
    profile.destroy
  end

  def edit
  end

  def update
    profile = Profile.find(params[:id])
    profile.update(profile_params)
  end

  def show
    @comment = Comment.new
    @comments = @profile.comments.includes(:user)
  end

  private

  def profile_params
    params.require(:profile).permit(:image, :position_id, :dexterity_id, :team, :age).merge(user_id: current_user.id)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @profiles = user.profiles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseballcommunity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="left_header">
        <h1 class="brand" >BaseballCommunity</h1>
      </div>
      <div class="right_header">
        <ul class="nav__wrapper">
          <li class="nav__item" >
            <% if user_signed_in? %>
            <%= current_user.name %>
            <%= link_to "トップページ", root_path, class: "nav__item" %>
            <%= link_to "マイページ", "/profiles/#{current_user.id}", class: "nav__item" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav__item" %>
            <%= link_to "プロフィール作成", new_profile_path, class: "nav__item" %>
            <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "nav__item" %>
            <%= link_to "新規登録", new_user_registration_path, class: "nav__item" %>
            <% end %>
          </li>
        </ul>
      </div>
    </header>

    <div class="top_image"></div>

    <%= yield %>

    <footer>
    </footer>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <p>画像のURL</p>
  <p><%= form.text_field :image, placeholder: "Image Url" %></p>
  <p>ポジション</p>
  <p><%= form.collection_select(:position_id, Position.all, :id, :name, {} ) %></p>
  <p>投/打</p>
  <p><%= form.collection_select(:dexterity_id, Dexterity.all, :id, :name, {} ) %></p>
  <p>チーム名 (所属していない方は「無所属」と記名)</p>
  <p><%= form.text_field :team %></p>
  <p>年齢 (半角数字)</p>
  <p><%= form.text_field :age %></p>
  <p class="actions"><%= form.submit "SEND" %></p>
<% end %>

app/views/profiles/_profile.html.erb
<div class="one_contents">
  <div class="profile_title">プロフィール</div>
  <div class="profile_button">
    <p class="profile_one_button">
      <%= link_to '詳細', profile_path(profile.id), method: :get %>
    </p>
    <% if user_signed_in? && current_user.id == profile.user_id %>
    <p class="profile_one_button">
      <%= link_to '編集', edit_profile_path(profile.id), method: :get %>
    </p>
    <p class="profile_one_button">
      <%= link_to '削除', profile_path(profile.id), method: :delete %>
    </p>
    <% end %>
  </div>
  <%= image_tag profile.image, class: 'profile_image' %>
  <p class="profile_element_name" href="/users/<%= profile.user.id %>">
    <%= profile.user.name %>
  </p>
  <p class="profile_element"><%= profile.position.name %></p>
  <p class="profile_element"><%= profile.dexterity.name %></p>
  <p class="profile_element"><%= profile.team %></p>
  <p class="profile_element_age"><%= profile.age %>歳</p>
</div>

app/views/profiles/create.html.erb
<div class="contents">
  <div class="title2">作成が完了しました。</div>
  <div class="login_contents">
    <div class="login_one_contents3">
      <div class="login_one_contents2">
        <a class="profile_end" href="/">トップページへ戻る</a>
      </div>
    </div>
  </div>
</div>

app/views/profiles/destroy.html.erb
<div class="contents row">
  <div class="title2">削除が完了しました。</div>
  <div class="login_contents">
    <div class="login_one_contents3">
      <div class="login_one_contents2">
        <a class="profile_end" href="/">トップページへ戻る</a>
      </div>
    </div>
  </div>



</div>

app/views/profiles/edit.html.erb
<div class="contents">
  <div class="title2">編集ページ</div>
  <div class="login_contents">
    <div class="login_one_contents">
      <div class="login_one_contents2">
        <%= render partial: "form", locals: { profile: @profile } %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="contents">

  <div class="top_image"><%= image_tag('baseball.jpg') %></div>
  <div class="title">トップページ</div>

  <div class="main_contents">
    <% if  @profiles.present? %>
      <% @profiles.each do |profile| %>
        <%= render partial: "profile", locals: { profile: profile } %>
      <% end %>
    <% else %>

      <div class="one_contents">
        <div class="profile_title">プロフィール</div>
        <div class="profile_button">
          <p class="profile_one_button">
            詳細
          </p>
          <p class="profile_one_button">
            編集
          </p>
          <p class="profile_one_button">
            削除
          </p>
        </div>
        <p class="profile_image2"></p>
        <p class="profile_element_name">
          名前
        </p>
        <p class="profile_element">ポジション</p>
        <p class="profile_element">投/打</p>
        <p class="profile_element">チーム名</p>
        <p class="profile_element_age">年齢</p>
      </div>

    <% end %>
  </div>

  <div class="footer">
    BaseballCommunity　　　※18~50歳の方が対象
  </div>

</div>

app/views/profiles/new.html.erb
<div class="contents">
  <div class="title2">プロフィール作成</div>
  <div class="login_contents">
    <div class="login_one_contents">
      <div class="login_one_contents2">
        <%= render partial: "form", locals: { profile: @profile } %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="contents">
  <div class="title2">マイページ</div>
  <div class="main_contents2">
    <div class="profile_title2">プロフィール</div>
    <div class="more">
      <% if user_signed_in? && current_user.id == @profile.user_id %>
      <p class="my_page_one_button">
        <%= link_to '編集', edit_profile_path(@profile.id), method: :get %>
      </p>
      <p class="my_page_one_button">
        <%= link_to '削除', profile_path(@profile.id), method: :delete %>
      </p>
      <% end %>
    </div>
    <%= image_tag @profile.image, class: 'my_page_image' %>
    <a class="my_page_element", href="/users/<%= @profile.user.id %>">
      <%= @profile.user.name %>
    </a>
    <p class="my_page_element"><%= @profile.position.name %></p>
    <p class="my_page_element"><%= @profile.dexterity.name %></p>
    <p class="my_page_element"><%= @profile.team %></p>
    <p class="my_page_element2"><%= @profile.age %>歳</p>

    
    <% if user_signed_in? %>
      <%= form_with(model: [@profile, @comment], local: true) do |form| %>
        <p class="my_page_element3"><%= form.text_area :text, placeholder: "コメントする", rows: "2" %></p>
        <p class="my_page_element3"><%= form.submit "SEND" %></p>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>


    <h1 class="my_page_element3">＜コメント一覧＞</h1>
    <% @comments.each do |comment| %>
      <p class="my_page_element4">
        <strong><%= link_to comment.user.name, "/profiles/#{comment.user_id}" %>：</strong>
        <%= comment.text %>
      </p>
    <% end %>
  </div>

  <div class="footer">
    BaseballCommunity
  </div>

</div>

app/views/profiles/update.html.erb
<div class="contents">
  <div class="title2">更新が完了しました。</div>
  <div class="login_contents">
    <div class="login_one_contents3">
      <div class="login_one_contents2">
        <a class="profile_end" href="/">トップページへ戻る</a>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents">
  <div class="title2"><%= @name %>さんのプロフィール一覧</div>

    <% @profiles.each do |profile| %>
      <div class="main_contents3">
        <%= image_tag profile.image, class: 'my_page_image2' %>
        <p class="my_page_element"><%= profile.position.name %></p>
        <p class="my_page_element"><%= profile.dexterity.name %></p>
        <p class="my_page_element"><%= profile.team %></p>
        <p class="my_page_element2"><%= profile.age %>歳</p>
      </div>
    <% end %>

  <div class="footer">
    BaseballCommunity
  </div>

</div>